### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by staenker** [aws/aws-lambda-runtime-interface-emulator#10]
~  aws-lambda-rie
zsh: exec format error: aws-lambda-rie
 ✘  ~ 

**Comment by jfuss** [comment]
Binary is compiled only for Linux: https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/main/Makefile#L11, as it is meant to run inside a container on the same OS/Arch as Lambda. So this is intentionally not supported. To test locally, add our mount the binary into a container, as described in the README.

**Comment by lamba92** [comment]
I believe that the initial table is very misleading. I also thought that using some kind of magic the executable was multiplatform. Indeed is not, at it should be, and only Linux is avutally supported. Please state that explicitely and remove the table.
