### ISSUE TITLE
Trying to test a simple lambda - getting Unable to unmarshal error

### ISSUE THREAD

**Issue by pokalas1015** [aws/aws-lambda-runtime-interface-emulator#128]
"Unable to unmarshal input: Expecting value: line 1 column 1 (char 0)"
Dockerfile: 
FROM public.ecr.aws/lambda/python:3.8
ADD aws-lambda-rie /usr/local/bin/aws-lambda-rie]

COPY entry_script.sh ./
COPY myfunction.py ./

CMD ["myfunction.lambda_handler"]

myfunction.py:
import json
import sys

def lambda_handler(event, context):
    print("Hello from AWS Lambda!")

**Comment by pokalas1015** [comment]
Sending Error Response: Runtime.Unknown
when turned on debug log level

**Comment by pokalas1015** [comment]
Worked!  Does not work with curl, works with Invoke_Web

**Comment by pokalas1015** [comment]
Close this issue

**Comment by valerena** [comment]
I'm interested to know what command you were running originally, but I'm glad it was resolved.

**Comment by pokalas1015** [comment]
Curl command, it does not work

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Jun 18, 2024 at 7:44 PM, Renato ***@***.***> wrote:   


I'm interested to know what command you were running originally, but I'm glad it was resolved.
