### ISSUE TITLE
Installing Windows "aws-lambda-runtime-interface-emulator " copies Linux binary to windows program files

### ISSUE THREAD

**Issue by madhub** [aws/aws-lambda-runtime-interface-emulator#132]
Followed the instruction provided to install "aws-lambda-runtime-interface-emulator" [on windows ](https://github.com/aws/aws-lambda-runtime-interface-emulator?tab=readme-ov-file#installing) , it copies Linux binary to program files.
Executed following command from powershell administrator prompt to install. Used **gitbash file** command to verify the binary 
```shell
Invoke-WebRequest -OutFile 'C:\Program Files\aws lambda\aws-lambda-rie' https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie
```
checked the file type from windows gitbash shell

![image](https://github.com/user-attachments/assets/dfe2195e-8e17-454c-a3b7-86d9c287f79f)

Please build windows binary & update the documentation

**Comment by valerena** [comment]
This binary emulates the Lambda runtime interface, which is only Amazon Linux, therefore is not expected to actually run on Windows. To use it correctly, you need a Docker base image that contains the actual Lambda runtime (this is just the interface with an underlying runtime). If you have an image function, then you can follow [the instructions in the README](https://github.com/aws/aws-lambda-runtime-interface-emulator?tab=readme-ov-file#getting-started). If you have a zip function, the easiest way to make use of this is to use [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) which uses RIE behind the scenes. In both cases, you need Docker.

**Comment by madhub** [comment]
> This binary emulates the Lambda runtime interface, which is only Amazon Linux, therefore is not expected to actually run on Windows. To use it correctly, you need a Docker base image that contains the actual Lambda runtime (this is just the interface with an underlying runtime). If you have an image function, then you can follow [the instructions in the README](https://github.com/aws/aws-lambda-runtime-interface-emulator?tab=readme-ov-file#getting-started). If you have a zip function, the easiest way to make use of this is to use [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) which uses RIE behind the scenes. In both cases, you need Docker.

Ok, got it

Just for clarification, what is windows installation step here 👇

![image](https://github.com/user-attachments/assets/d7577f12-97f2-4c6e-91f4-b411c1bd2373)

**Comment by valerena** [comment]
That installation basically downloads the latest version of RIE into your Windows machine (for the corresponding platform). With that latest version you can then do the instructions to [Build RIE into your base image](https://github.com/aws/aws-lambda-runtime-interface-emulator?tab=readme-ov-file#build-rie-into-your-base-image)
