### ISSUE TITLE
RIE not working on debian with no output

### ISSUE THREAD

**Issue by poliak9** [aws/aws-lambda-runtime-interface-emulator#22]
Hi,
I am trying to create a python lambda on debian using the `python:3.8-buster` as docker base. When i tried using the rie I've got no success and no error reported why it's not working. The simplest example i could find to reproduce is simply running the base debian image with the RIE mounted in:
```
docker run -v ~/.aws-lambda-rie:/aws-lambda -p 9000:8080 \ 
    --entrypoint /aws-lambda/aws-lambda-rie \
        -t python:3.8-buster --log-level debug  python -m awslambdaric entry.handler
```
I get the output
```
INFO[0000] exec 'python' (cwd=/, handler=entry.handler)
DEBU[0000] Runtime API Server listening on 127.0.0.1:9001
```
I would expect to get some error (for example that `awslambdaric` is not installed). It behaves the same when I mistype `python` to let's say `pymton` - no error reported.

Running `docker exec angry_proskuriakova ps -A` shows rie running
```
  PID TTY          TIME CMD
    1 pts/0    00:00:00 aws-lambda-rie
   12 ?        00:00:00 ps
```
 After `ctrl-C` it exits correctly so I assume that rie is still running, but silently failed running the lambda
 ```
INFO[0211] Received signal                               signal=interrupt
INFO[0211] Shutting down...
DEBU[0211] Canceling flows: errResetReceived
WARN[0211] Reset initiated: SandboxTerminated
DEBU[0211] Dispatching DONE:resetCorrelationID
```

Could you please confirm that this is happening or tell me what I'm doing wrong?

**Comment by jfuss** [comment]
@poliak9 After you run the image, you need to send a request to `127.0.0.1:9001`. Details can be found here: https://github.com/aws/aws-lambda-runtime-interface-emulator#test-an-image-without-adding-rie-to-the-image under Step 3. Is that not working for you?

**Comment by poliak9** [comment]
@jfuss thanks for the response. I am aware about the endpoint. The problem I have is that it is not responding at all (I don't know why) and I found out it doesn't **say** why, so I created this example where the app can't load (because of the typo) and doesn't report any error

**Comment by poliak9** [comment]
Also the ports are kinda messy, as it says it logs listening on port `9001` but the examples use `-p 9000:8080`. However, I tried binding to the other ports as well without any success

**Comment by poliak9** [comment]
Ah sorry my bad the problem was somewhere else.

**Comment by bruce-szalwinski** [comment]
> Ah sorry my bad the problem was somewhere else.

Can you provide more info here?
