### ISSUE TITLE
Test lambda that has websocket routes

### ISSUE THREAD

**Issue by diegosasw** [aws/aws-lambda-runtime-interface-emulator#25]
Not sure if it's possible with this approach, but suppose the lambda is the back-end for an API Gateway that uses websockets. How could this be tested using this interface emulator?

I haven't been able to find details on how an event to invoke a lambda function looks like when using web sockets.

I know for a REST Api this is a valid event
```
{
  "resource": "/{proxy+}",
  "path": "/api/values",
  "httpMethod": "GET",
  "headers": null,
  "queryStringParameters": null,
  "pathParameters": {
    "proxy": "api/values"
  },
  "stageVariables": null,
  "requestContext": {
    "accountId": "AAAAAAAAAAAA",
    "resourceId": "5agfss",
    "stage": "test-invoke-stage",
    "requestId": "test-invoke-request",
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": "AAAAAAAAAAAA",
      "cognitoIdentityId": null,
      "caller": "BBBBBBBBBBBB",
      "apiKey": "test-invoke-api-key",
      "sourceIp": "test-invoke-source-ip",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": "arn:aws:iam::AAAAAAAAAAAA:root",
      "userAgent": "Apache-HttpClient/4.5.x (Java/1.8.0_102)",
      "user": "AAAAAAAAAAAA"
    },
    "resourcePath": "/{proxy+}",
    "httpMethod": "GET",
    "apiId": "t2yh6sjnmk"
  },
  "body": null
}
```

and therefore, if I save it in a `test_request.json` I could test the lambda function like this with CURL when running in the emulator

```
curl -vX POST http://localhost:9000/2015-03-31/functions/function/invocations -d @test_request.json --header "Content-Type: application/json"
```

Is there anything similar when the event represents a `$connect`, `$disconnect` or `sendmessage` message from Api Gateway websocket to lambda?

**Comment by jfuss** [comment]
@diegosasw I don't really understand your question. You can send whatever payload you need to the function. In the case of API Gateway, you should be able to model what input as if it was the Service doing the invoke for you.

I think the answer is yes, but you have to construct that json data to send to the function through the `curl` post call.

**Comment by diegosasw** [comment]
@jfuss 
Thanks. I found out the payloads below

```
$connect
```
{
    "headers": {
        "Host": "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com",
        "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
        "Sec-WebSocket-Key": "ElxPGSkjS67JEzN6/32V1A==",
        "Sec-WebSocket-Version": "13",
        "X-Amzn-Trace-Id": "Root=1-60351922-7cd582b44021ba371d4b975b",
        "X-Forwarded-For": "185.153.165.121",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Host": [
            "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com"
        ],
        "Sec-WebSocket-Extensions": [
            "permessage-deflate; client_max_window_bits"
        ],
        "Sec-WebSocket-Key": [
            "ElxPGSkjS67JEzN6/32V1A=="
        ],
        "Sec-WebSocket-Version": [
            "13"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-60351922-7cd582b44021ba371d4b975b"
        ],
        "X-Forwarded-For": [
            "185.153.165.121"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "requestContext": {
        "routeKey": "$connect",
        "disconnectStatusCode": null,
        "messageId": null,
        "eventType": "CONNECT",
        "extendedRequestId": "bNDdbEgZCGYFjXQ=",
        "requestTime": "23/Feb/2021:15:02:58 +0000",
        "messageDirection": "IN",
        "disconnectReason": null,
        "stage": "production",
        "connectedAt": 1614092578600,
        "requestTimeEpoch": 1614092578601,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "185.153.165.121",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "bNDdbEgZCGYFjXQ=",
        "domainName": "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com",
        "connectionId": "bNDdbfUjCGYCG1Q=",
        "apiId": "82a1kbz4gh"
    },
    "isBase64Encoded": false
}
```
sendmessage
```
{
    "requestContext": {
        "routeKey": "$default",
        "disconnectStatusCode": null,
        "messageId": "bNDfrfU9iGYCG1Q=",
        "eventType": "MESSAGE",
        "extendedRequestId": "bNDfrFlQiGYFlnQ=",
        "requestTime": "23/Feb/2021:15:03:13 +0000",
        "messageDirection": "IN",
        "disconnectReason": null,
        "stage": "production",
        "connectedAt": 1614092578600,
        "requestTimeEpoch": 1614092593017,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "185.153.165.121",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "bNDfrFlQiGYFlnQ=",
        "domainName": "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com",
        "connectionId": "bNDdbfUjCGYCG1Q=",
        "apiId": "82a1kbz4gh"
    },
    "body": "{\"foo\":\"sendmessage\", \"message\":\"hello world\"}",
    "isBase64Encoded": false
}
```

$disconnect
```
{
    "headers": {
        "Host": "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com",
        "x-api-key": "",
        "X-Forwarded-For": "",
        "x-restapi": ""
    },
    "multiValueHeaders": {
        "Host": [
            "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com"
        ],
        "x-api-key": [
            ""
        ],
        "X-Forwarded-For": [
            ""
        ],
        "x-restapi": [
            ""
        ]
    },
    "requestContext": {
        "routeKey": "$disconnect",
        "disconnectStatusCode": -1,
        "messageId": null,
        "eventType": "DISCONNECT",
        "extendedRequestId": "bNDh2HilCGYFjww=",
        "requestTime": "23/Feb/2021:15:03:26 +0000",
        "messageDirection": "IN",
        "disconnectReason": "",
        "stage": "production",
        "connectedAt": 1614092578600,
        "requestTimeEpoch": 1614092606967,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "185.153.165.121",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "bNDh2HilCGYFjww=",
        "domainName": "82a1kbz4gh.execute-api.eu-west-3.amazonaws.com",
        "connectionId": "bNDdbfUjCGYCG1Q=",
        "apiId": "82a1kbz4gh"
    },
    "isBase64Encoded": false
}
```

That's what I was looking for, mainly the payload for `$connect` and `$disconnect`, so it's all good.

I've got other issues outside lambda with Api Gateway and websocket when using HTTP integration instead of Lambda, like described here https://stackoverflow.com/questions/66688751/extract-websocket-connection-id-and-other-details-from-websocket-in-aws-api-gate but that's a different question.

Closing this as it's clear, thanks again.
