### ISSUE TITLE
Change timeout?

### ISSUE THREAD

**Issue by aCampello** [aws/aws-lambda-runtime-interface-emulator#27]
Is it possible to change the timeout using the RIE? Currently it seems that it is set to 300s, however the Lambda functions can now run up to 15 minutes

**Comment by jfuss** [comment]
You can configure the timeout through an Env Var. Details are in the our [README](https://github.com/aws/aws-lambda-runtime-interface-emulator#how-to-configure).

"You can configure timeout by setting AWS_LAMBDA_FUNCTION_TIMEOUT to the number of seconds you want your function to timeout in."
