### ISSUE TITLE
release binaries that work on mac

### ISSUE THREAD

**Issue by teyckmans** [aws/aws-lambda-runtime-interface-emulator#55]
Would be nice to have binaries included on a release that target Mac.

For now I had to change the Makefile to build for `GOOS=darwin` as a work around.

**Comment by teyckmans** [comment]
I am trying to create graalvm native-image lambdas, the easiest way for now is to run the emulator with the lambda as a java process and use the graalvm agent that collects all the graalvm config during test execution, after that I can use the gathered config to produce a native-image.

Currently I am just doing this locally on a mac, I can also do that through docker.

**Comment by wichert** [comment]
Shouldn't this be reopened? The README is pretty clear that macOS is supported, but the install instructions give you a Linux-only binary.

**Comment by kdemkin** [comment]
It's not a big deal to build it for macOS
`CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o bin/aws-lambda-rie-arm64 ./cmd/aws-lambda-rie bin/aws-lambda-rie-arm64`

But I agree with @wichert, the binary attached to the README won't work on Apple Silicone macs.
